/**
 * File generated by Magnet rest2mobile 1.1 - Jul 14, 2015 12:24:18 AM
 * @see {@link http://developer.magnet.com}
 */

package com.example.anthony.bigscreenforreddit.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.example.anthony.bigscreenforreddit.model.beans.*;

public class RedditMagnetAPIFactory extends ControllerFactory<RedditMagnetAPI> {
  public RedditMagnetAPIFactory(MagnetMobileClient magnetClient) {
    super(RedditMagnetAPI.class, RedditMagnetAPISchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller RedditMagnetAPI
  public static class RedditMagnetAPISchemaFactory extends AbstractControllerSchemaFactory {
    private static RedditMagnetAPISchemaFactory __instance;

    public static synchronized RedditMagnetAPISchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new RedditMagnetAPISchemaFactory();
      }

      return __instance;
    }

    private RedditMagnetAPISchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getSubredditFeed
      JMethod method1 = addMethod("getSubredditFeed",
        "r/{subReddit}/.json",
        "GET",
        SubredditFeedResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://www.reddit.com");
      method1.addParam("subReddit",
        "TEMPLATE",
        String.class,
        null,
        "",
        false);
    }

  }

}
