/**
 * File generated by Magnet rest2mobile 1.1 - Jul 14, 2015 12:24:18 AM
 * @see {@link http://developer.magnet.com}
 */

package com.example.anthony.bigscreenforreddit.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.example.anthony.bigscreenforreddit.model.beans.*;

public interface RedditMagnetAPI {

  /**
   * Generated from URL GET https://www.reddit.com/r/{subReddit}/.json
   * GET r/{subReddit}/.json
   * @param subReddit  style:TEMPLATE
   * @param listener
   * @return SubredditFeedResult
   */
  Call<SubredditFeedResult> getSubredditFeed(
     String subReddit,
     StateChangedListener listener
  );


}
