/**
 * File generated by Magnet rest2mobile 1.1 - Jul 14, 2015 12:24:19 AM
 * @see {@link http://developer.magnet.com}
 */

package com.example.anthony.bigscreenforreddit.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.example.anthony.bigscreenforreddit.controller.api.RedditMagnetAPI;
import com.example.anthony.bigscreenforreddit.controller.api.RedditMagnetAPIFactory;
import com.example.anthony.bigscreenforreddit.model.beans.*;

/**
* This is generated stub to test {@link RedditMagnetAPI}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class RedditMagnetAPITest extends InstrumentationTestCase {
  private RedditMagnetAPI redditMagnetAPI;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    RedditMagnetAPIFactory controllerFactory = new RedditMagnetAPIFactory(magnetClient);
    redditMagnetAPI = controllerFactory.obtainInstance();

    assertNotNull(redditMagnetAPI);
  }

  /**
    * Generated unit test for {@link RedditMagnetAPI#getSubredditFeed}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testGetSubredditFeed() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String subReddit = null;

    Call<SubredditFeedResult> callObject = redditMagnetAPI.getSubredditFeed(
      subReddit, null);
    assertNotNull(callObject);

    SubredditFeedResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
